// Auto-generated by scripts/convert-sakuraflow.js from SakuraFlow scrape
// Source: https://www.sakuraflow.app/basics — 141 leçons
// Images: /public/kana-mnemonics/ (downloaded locally)
// DO NOT EDIT MANUALLY — regenerate with: node scripts/convert-sakuraflow.js

export type KanaSlide = {
  type: "kana";
  char: string;
  romaji: string;
  mnemonic: string;
  image: string;
  description: string;
};

export type VocabSlide = {
  type: "vocab";
  word: string;
  romaji: string;
  meaning: string;
  meaningFr: string;
  image: string;
};

export type Slide = KanaSlide | VocabSlide;

export type Exercise = {
  id: string;
  type: "kana_to_romaji" | "romaji_to_kana" | "word_to_meaning" | "meaning_to_word"
      | "write_romaji" | "write_jp";
  prompt: string;
  promptSub?: string;
  answer: string;        // bonne réponse à afficher
  choices: string[];     // vide pour les types "write_*"
  accept?: string[];     // saisies acceptées (normalisées) pour les "write_*"
};

export type LessonKind = "kana" | "word" | "practice" | "review" | "quiz";

export type BasicsLesson = {
  id: number;        // contiguous 1..N, in real course order (routing key)
  realId: number;    // original SakuraFlow lesson number
  chapter: number;   // 1..10 (see BASICS_CHAPTERS)
  kind: LessonKind;  // badge + comportement (contenu vs drill d'exercices)
  drill: boolean;    // true = pas de slides, exercices sur le vocabulaire acquis
  title: string;
  subtitle: string;
  emoji: string;
  xp: number;
  newCount: number;
  slides: Slide[];
};

export type BasicsChapter = { num: number; name: string; subtitle: string; total: number };

// Les 10 chapitres SakuraFlow — noms, sous-titres et nombre total de leçons
// exacts (issus du cours original). "total" = nombre de leçons SakuraFlow ;
// toutes ne sont pas encore jouables ici (les sessions de révision/quiz).
export const BASICS_CHAPTERS: BasicsChapter[] = [
  { num: 1,  name: "Hiragana — Début",            subtitle: "Premiers pas avec les hiragana",                 total: 17 },
  { num: 2,  name: "Hiragana au quotidien",       subtitle: "Plus de caractères et phrases du quotidien",     total: 20 },
  { num: 3,  name: "Hiragana complet",            subtitle: "Les rangées restantes : ま, や, ら, わ",           total: 14 },
  { num: 4,  name: "Katakana — Début",            subtitle: "À la découverte des caractères anguleux",        total: 28 },
  { num: 5,  name: "Maîtrise du katakana",        subtitle: "Maîtrise tous les katakana",                     total: 26 },
  { num: 6,  name: "Caractères spéciaux",         subtitle: "Maîtrise っ, les yōon et voyelles longues",       total: 10 },
  { num: 7,  name: "Nombres & premiers kanji",    subtitle: "ichi–juu et 一–十 : tes premiers kanji",          total: 3 },
  { num: 8,  name: "Compteurs & comptage",        subtitle: "ひとつ, 〜にん, 〜さい, 〜じ — compter en japonais",   total: 8 },
  { num: 9,  name: "Démonstratifs & questions",   subtitle: "これ・それ・あれ, mots interrogatifs et langues",   total: 8 },
  { num: 10, name: "Quotidien & expressions",     subtitle: "Phrases pratiques pour la vie au Japon",         total: 7 },
];

// ── Hiragana distractor pool ──────────────────────────────────────────────────
const ALL_HIRAGANA: { char: string; romaji: string }[] = [
  { char: "あ", romaji: "a" }, { char: "い", romaji: "i" }, { char: "う", romaji: "u" },
  { char: "え", romaji: "e" }, { char: "お", romaji: "o" },
  { char: "か", romaji: "ka" }, { char: "き", romaji: "ki" }, { char: "く", romaji: "ku" },
  { char: "け", romaji: "ke" }, { char: "こ", romaji: "ko" },
  { char: "さ", romaji: "sa" }, { char: "し", romaji: "shi" }, { char: "す", romaji: "su" },
  { char: "せ", romaji: "se" }, { char: "そ", romaji: "so" },
  { char: "た", romaji: "ta" }, { char: "ち", romaji: "chi" }, { char: "つ", romaji: "tsu" },
  { char: "て", romaji: "te" }, { char: "と", romaji: "to" },
  { char: "な", romaji: "na" }, { char: "に", romaji: "ni" }, { char: "ぬ", romaji: "nu" },
  { char: "ね", romaji: "ne" }, { char: "の", romaji: "no" },
  { char: "は", romaji: "ha" }, { char: "ひ", romaji: "hi" }, { char: "ふ", romaji: "fu" },
  { char: "へ", romaji: "he" }, { char: "ほ", romaji: "ho" },
  { char: "ま", romaji: "ma" }, { char: "み", romaji: "mi" }, { char: "む", romaji: "mu" },
  { char: "め", romaji: "me" }, { char: "も", romaji: "mo" },
  { char: "や", romaji: "ya" }, { char: "ゆ", romaji: "yu" }, { char: "よ", romaji: "yo" },
  { char: "ら", romaji: "ra" }, { char: "り", romaji: "ri" }, { char: "る", romaji: "ru" },
  { char: "れ", romaji: "re" }, { char: "ろ", romaji: "ro" },
  { char: "わ", romaji: "wa" }, { char: "を", romaji: "wo" }, { char: "ん", romaji: "n" },
  // Dakuten hiragana
  { char: "が", romaji: "ga" }, { char: "ぎ", romaji: "gi" }, { char: "ぐ", romaji: "gu" },
  { char: "げ", romaji: "ge" }, { char: "ご", romaji: "go" },
  { char: "ざ", romaji: "za" }, { char: "じ", romaji: "ji" }, { char: "ず", romaji: "zu" },
  { char: "ぜ", romaji: "ze" }, { char: "ぞ", romaji: "zo" },
  { char: "だ", romaji: "da" }, { char: "ぢ", romaji: "ji" }, { char: "づ", romaji: "zu" },
  { char: "で", romaji: "de" }, { char: "ど", romaji: "do" },
  { char: "ば", romaji: "ba" }, { char: "び", romaji: "bi" }, { char: "ぶ", romaji: "bu" },
  { char: "べ", romaji: "be" }, { char: "ぼ", romaji: "bo" },
  { char: "ぱ", romaji: "pa" }, { char: "ぴ", romaji: "pi" }, { char: "ぷ", romaji: "pu" },
  { char: "ぺ", romaji: "pe" }, { char: "ぽ", romaji: "po" },
];

const ALL_KATAKANA: { char: string; romaji: string }[] = [
  { char: "ア", romaji: "a" }, { char: "イ", romaji: "i" }, { char: "ウ", romaji: "u" },
  { char: "エ", romaji: "e" }, { char: "オ", romaji: "o" },
  { char: "カ", romaji: "ka" }, { char: "キ", romaji: "ki" }, { char: "ク", romaji: "ku" },
  { char: "ケ", romaji: "ke" }, { char: "コ", romaji: "ko" },
  { char: "サ", romaji: "sa" }, { char: "シ", romaji: "shi" }, { char: "ス", romaji: "su" },
  { char: "セ", romaji: "se" }, { char: "ソ", romaji: "so" },
  { char: "タ", romaji: "ta" }, { char: "チ", romaji: "chi" }, { char: "ツ", romaji: "tsu" },
  { char: "テ", romaji: "te" }, { char: "ト", romaji: "to" },
  { char: "ナ", romaji: "na" }, { char: "ニ", romaji: "ni" }, { char: "ヌ", romaji: "nu" },
  { char: "ネ", romaji: "ne" }, { char: "ノ", romaji: "no" },
  { char: "ハ", romaji: "ha" }, { char: "ヒ", romaji: "hi" }, { char: "フ", romaji: "fu" },
  { char: "ヘ", romaji: "he" }, { char: "ホ", romaji: "ho" },
  { char: "マ", romaji: "ma" }, { char: "ミ", romaji: "mi" }, { char: "ム", romaji: "mu" },
  { char: "メ", romaji: "me" }, { char: "モ", romaji: "mo" },
  { char: "ヤ", romaji: "ya" }, { char: "ユ", romaji: "yu" }, { char: "ヨ", romaji: "yo" },
  { char: "ラ", romaji: "ra" }, { char: "リ", romaji: "ri" }, { char: "ル", romaji: "ru" },
  { char: "レ", romaji: "re" }, { char: "ロ", romaji: "ro" },
  { char: "ワ", romaji: "wa" }, { char: "ヲ", romaji: "wo" }, { char: "ン", romaji: "n" },
];

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ── Exercise generation ───────────────────────────────────────────────────────
export function generateExercises(lesson: BasicsLesson): Exercise[] {
  const exercises: Exercise[] = [];
  const kanaSlides  = lesson.slides.filter((s): s is KanaSlide  => s.type === "kana");
  const vocabSlides = lesson.slides.filter((s): s is VocabSlide => s.type === "vocab");

  // Detect script (hiragana vs katakana)
  const isKatakana = kanaSlides.some(s => /[ア-ヶ]/.test(s.char));
  const distPool = isKatakana ? ALL_KATAKANA : ALL_HIRAGANA;

  for (const slide of kanaSlides) {
    const lessonRomajis = kanaSlides.map(k => k.romaji);

    const romajiSeen = new Set<string>();
    const romajiPool: string[] = [];
    for (const r of [...lessonRomajis, ...distPool.map(k => k.romaji)]) {
      if (r !== slide.romaji && !romajiSeen.has(r)) { romajiSeen.add(r); romajiPool.push(r); }
    }
    // Distracteurs kana : on exclut le bon caractère ET tout homophone
    // (même rōmaji, ex. じ/ぢ, づ/ず) pour éviter deux réponses correctes.
    const charSeen = new Set<string>();
    const charPool: string[] = [];
    for (const entry of [...kanaSlides, ...distPool]) {
      if (entry.char === slide.char || entry.romaji === slide.romaji) continue;
      if (charSeen.has(entry.char)) continue;
      charSeen.add(entry.char);
      charPool.push(entry.char);
    }

    exercises.push({
      id: `${lesson.id}-ktr-${slide.romaji}`,
      type: "kana_to_romaji",
      prompt: slide.char,
      promptSub: isKatakana ? "Comment se prononce ce katakana ?" : "Comment se prononce ce hiragana ?",
      answer: slide.romaji,
      choices: shuffle([slide.romaji, ...romajiPool.slice(0, 3)]),
    });
    exercises.push({
      id: `${lesson.id}-rtk-${slide.char}`,
      type: "romaji_to_kana",
      prompt: slide.romaji,
      promptSub: isKatakana ? "Quel est le katakana correspondant ?" : "Quel est le hiragana correspondant ?",
      answer: slide.char,
      choices: shuffle([slide.char, ...charPool.slice(0, 3)]),
    });
    // Saisie libre : on montre le kana, on écrit le rōmaji
    exercises.push({
      id: `${lesson.id}-wr-${slide.char}`,
      type: "write_romaji",
      prompt: slide.char,
      promptSub: isKatakana ? "Écris ce katakana en rōmaji" : "Écris ce hiragana en rōmaji",
      answer: slide.romaji,
      choices: [],
      accept: [slide.romaji],
    });
  }

  const allMeanings = vocabSlides.map(v => v.meaningFr);
  const allWords    = vocabSlides.map(v => v.word);
  const EXTRA_MEANINGS = ["Eau", "Maison", "Chat", "Soleil", "École", "Nuit", "Rue", "Jardin", "Livre", "Train", "Avion", "Mer", "Fleur", "Oiseau", "Vent"];

  for (const slide of vocabSlides) {
    // IMPORTANT : exclure la bonne réponse de TOUS les distracteurs (y compris
    // EXTRA_MEANINGS) sinon une carte distracteur peut être aussi correcte.
    const wrongMeanings = [...allMeanings, ...EXTRA_MEANINGS]
      .filter(m => m && m !== slide.meaningFr)
      .filter((v, i, arr) => arr.indexOf(v) === i)
      .slice(0, 3);
    exercises.push({
      id: `${lesson.id}-wtm-${slide.romaji}`,
      type: "word_to_meaning",
      prompt: slide.word,
      promptSub: slide.romaji,
      answer: slide.meaningFr,
      choices: shuffle([slide.meaningFr, ...wrongMeanings]),
    });

    const wrongWords = allWords.filter(w => w !== slide.word).slice(0, 3);
    if (wrongWords.length === 3) {
      exercises.push({
        id: `${lesson.id}-mtw-${slide.romaji}`,
        type: "meaning_to_word",
        prompt: slide.meaningFr,
        promptSub: "Choisir le mot japonais",
        answer: slide.word,
        choices: shuffle([slide.word, ...wrongWords]),
      });
    }
    // Saisie libre : on montre le sens français, on écrit le mot en japonais
    // (kana OU rōmaji accepté)
    exercises.push({
      id: `${lesson.id}-wj-${slide.romaji}`,
      type: "write_jp",
      prompt: slide.meaningFr,
      promptSub: "Écris le mot en japonais (kana ou rōmaji)",
      answer: slide.word,
      choices: [],
      accept: [slide.word, slide.romaji],
    });
  }

  return shuffle(exercises).slice(0, 16);
}

// ── Exercices pour une leçon, drills inclus ───────────────────────────────────
// Une leçon "drill" (practice/review/quiz sans slides) tire son vocabulaire des
// leçons de contenu déjà apprises : même chapitre pour un entraînement, tout le
// programme vu jusque-là pour une révision / un quiz.
export function buildLessonExercises(lesson: BasicsLesson, all: BasicsLesson[]): Exercise[] {
  if (!lesson.drill) return generateExercises(lesson);

  const pool = all.filter(
    (l) => !l.drill && l.slides.length > 0 && l.realId < lesson.realId &&
      (lesson.kind === "practice" ? l.chapter === lesson.chapter : l.chapter <= lesson.chapter)
  );
  let slides = pool.flatMap((l) => l.slides);
  // Repli : si rien dans la portée (rare), prendre tout l'acquis.
  if (slides.length === 0) {
    slides = all.filter((l) => !l.drill && l.realId < lesson.realId).flatMap((l) => l.slides);
  }
  const seen = new Set<string>();
  const uniq = slides.filter((s) => {
    const k = s.type === "kana" ? "k:" + s.char : "v:" + s.word;
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
  const count = lesson.kind === "quiz" ? 20 : 12;
  return generateExercises({ ...lesson, slides: shuffle(uniq).slice(0, count * 2) }).slice(0, count);
}

// ── Lesson data (141 leçons) ─────────────────────────────────────────────────────
export const ALL_LESSONS: BasicsLesson[] = [
  {
    id: 1, realId: 1, chapter: 1, kind: "kana", drill: false,
    title: "あいうえお", subtitle: "Les 5 voyelles — tes tout premiers hiragana",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "あ", romaji: "a",
        mnemonic: "あ is hiding inside an apple: like the \"A\" in apple.",
        image: "/kana-mnemonics/a-apple.webp",
        description: "This hiragana character stands for the sound a." },
      { type: "kana", char: "い", romaji: "i",
        mnemonic: "Two little girls stand side by side and together they spell \"ii\".",
        image: "/kana-mnemonics/i-twogirls.webp",
        description: "This hiragana character stands for the sound i." },
      { type: "kana", char: "う", romaji: "u",
        mnemonic: "Someone bends forward in surprise and goes \"uuh!\".",
        image: "/kana-mnemonics/u-uhh.webp",
        description: "This hiragana character stands for the sound u." },
      { type: "kana", char: "え", romaji: "e",
        mnemonic: "An energetic ninja leaps into action: \"energetic\" starts with \"e\".",
        image: "/kana-mnemonics/e-ninja.webp",
        description: "This hiragana character stands for the sound e." },
      { type: "kana", char: "お", romaji: "o",
        mnemonic: "A U.F.O. gently lands: and the \"O\" sits right in the middle.",
        image: "/kana-mnemonics/o-ufo.webp",
        description: "This hiragana character stands for the sound o." }
    ],
  },
  {
    id: 2, realId: 2, chapter: 1, kind: "word", drill: false,
    title: "Premiers petits mots", subtitle: "あい・あお・うえ — applique tout de suite",
    emoji: "💬", xp: 20, newCount: 3,
    slides: [
      { type: "vocab", word: "あい", romaji: "ai",
        meaning: "Love", meaningFr: "Amour",
        image: "/kana-mnemonics/word-ai.webp" },
      { type: "vocab", word: "あお", romaji: "ao",
        meaning: "Blue", meaningFr: "Bleu",
        image: "/kana-mnemonics/word-ao.webp" },
      { type: "vocab", word: "うえ", romaji: "ue",
        meaning: "Above", meaningFr: "Au-dessus",
        image: "/kana-mnemonics/word-ue.webp" }
    ],
  },
  {
    id: 3, realId: 3, chapter: 1, kind: "practice", drill: true,
    title: "Entraînement : les voyelles", subtitle: "Révision rapide de あいうえお",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 4, realId: 4, chapter: 1, kind: "kana", drill: false,
    title: "かきくけこ", subtitle: "La rangée K",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "か", romaji: "ka",
        mnemonic: "A curved katana blade: katana → ka.",
        image: "/kana-mnemonics/ka-katana.webp",
        description: "This hiragana character stands for the sound ka." },
      { type: "kana", char: "き", romaji: "ki",
        mnemonic: "An old-fashioned key with bow and bit: key → ki.",
        image: "/kana-mnemonics/ki-key.webp",
        description: "This hiragana character stands for the sound ki." },
      { type: "kana", char: "く", romaji: "ku",
        mnemonic: "A cuckoo bird calling out \"ku-ku!\": cuckoo → ku.",
        image: "/kana-mnemonics/ku-cuckoo.webp",
        description: "This hiragana character stands for the sound ku." },
      { type: "kana", char: "け", romaji: "ke",
        mnemonic: "A tipped-over keg with a dripping tap: keg → ke.",
        image: "/kana-mnemonics/ke-keg.webp",
        description: "This hiragana character stands for the sound ke." },
      { type: "kana", char: "こ", romaji: "ko",
        mnemonic: "A playful koi fish gliding through the water: koi → ko.",
        image: "/kana-mnemonics/ko-koi.webp",
        description: "This hiragana character stands for the sound ko." }
    ],
  },
  {
    id: 5, realId: 5, chapter: 1, kind: "word", drill: false,
    title: "Mots en K", subtitle: "Tes premiers vrais mots avec か–こ",
    emoji: "💬", xp: 20, newCount: 5,
    slides: [
      { type: "vocab", word: "かお", romaji: "kao",
        meaning: "Face", meaningFr: "Visage",
        image: "/kana-mnemonics/word-kao.webp" },
      { type: "vocab", word: "えき", romaji: "eki",
        meaning: "Station", meaningFr: "Gare",
        image: "/kana-mnemonics/word-eki.webp" },
      { type: "vocab", word: "いく", romaji: "iku",
        meaning: "to go", meaningFr: "Aller",
        image: "/kana-mnemonics/word-iku.webp" },
      { type: "vocab", word: "いけ", romaji: "ike",
        meaning: "Pond", meaningFr: "Étang",
        image: "/kana-mnemonics/word-ike.webp" },
      { type: "vocab", word: "こえ", romaji: "koe",
        meaning: "Voice", meaningFr: "Voix",
        image: "/kana-mnemonics/word-koe.webp" }
    ],
  },
  {
    id: 6, realId: 6, chapter: 1, kind: "practice", drill: true,
    title: "Entraînement : rangée K", subtitle: "Drille かきくけこ et les mots en K",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 7, realId: 7, chapter: 1, kind: "practice", drill: true,
    title: "Entraînement : rangée K", subtitle: "Révision rapide か–こ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 8, realId: 8, chapter: 1, kind: "word", drill: false,
    title: "Mots en G (が–ご)", subtitle: "かぎ, えいが, かいぎ…",
    emoji: "💬", xp: 20, newCount: 2,
    slides: [
      { type: "vocab", word: "えいが", romaji: "eiga",
        meaning: "Movie", meaningFr: "Film",
        image: "/kana-mnemonics/word-eiga.webp" },
      { type: "vocab", word: "かいぎ", romaji: "kaigi",
        meaning: "Meeting", meaningFr: "Réunion",
        image: "/kana-mnemonics/word-kaigi.webp" }
    ],
  },
  {
    id: 9, realId: 9, chapter: 1, kind: "practice", drill: true,
    title: "Entraînement : rangée G", subtitle: "Drille が–ご",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 10, realId: 10, chapter: 1, kind: "kana", drill: false,
    title: "さしすせそ", subtitle: "La rangée S (し = shi)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "さ", romaji: "sa",
        mnemonic: "A sad little face with a single tear: sad → sa.",
        image: "/kana-mnemonics/sa-sad.webp",
        description: "This hiragana character stands for the sound sa." },
      { type: "kana", char: "し", romaji: "shi",
        mnemonic: "A single fishing hook dropping into the water: \"sheee…\" as it goes in.",
        image: "/kana-mnemonics/shi-hook.webp",
        description: "This hiragana character stands for the sound shi." },
      { type: "kana", char: "す", romaji: "su",
        mnemonic: "A straw poking out of a sweet drink: straw → su.",
        image: "/kana-mnemonics/su-straw.webp",
        description: "This hiragana character stands for the sound su." },
      { type: "kana", char: "せ", romaji: "se",
        mnemonic: "An open mouth mid-\"say!\": shouting a \"se\".",
        image: "/kana-mnemonics/se-saying.webp",
        description: "This hiragana character stands for the sound se." },
      { type: "kana", char: "そ", romaji: "so",
        mnemonic: "A thread with a tiny stitch: sew/stitch → so.",
        image: "/kana-mnemonics/so-stitch.webp",
        description: "This hiragana character stands for the sound so." }
    ],
  },
  {
    id: 11, realId: 11, chapter: 1, kind: "word", drill: false,
    title: "Mots déjà lisibles", subtitle: "Ta première vraie lecture",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "すし", romaji: "sushi",
        meaning: "Sushi", meaningFr: "Sushi",
        image: "/kana-mnemonics/word-sushi.webp" },
      { type: "vocab", word: "あさ", romaji: "asa",
        meaning: "Morning", meaningFr: "Matin",
        image: "/kana-mnemonics/word-asa.webp" },
      { type: "vocab", word: "ここ", romaji: "koko",
        meaning: "Here", meaningFr: "Ici",
        image: "/kana-mnemonics/word-koko.webp" },
      { type: "vocab", word: "さくら", romaji: "sakura",
        meaning: "Cherry blossom", meaningFr: "Fleur de cerisier",
        image: "/kana-mnemonics/word-sakura.webp" }
    ],
  },
  {
    id: 12, realId: 12, chapter: 1, kind: "word", drill: false,
    title: "Mots en S", subtitle: "Mots du quotidien avec さ–そ",
    emoji: "💬", xp: 20, newCount: 5,
    slides: [
      { type: "vocab", word: "かさ", romaji: "kasa",
        meaning: "Umbrella", meaningFr: "Parapluie",
        image: "/kana-mnemonics/word-kasa.webp" },
      { type: "vocab", word: "いす", romaji: "isu",
        meaning: "Chair", meaningFr: "Chaise",
        image: "/kana-mnemonics/word-isu.webp" },
      { type: "vocab", word: "あし", romaji: "ashi",
        meaning: "Foot", meaningFr: "Pied",
        image: "/kana-mnemonics/word-ashi.webp" },
      { type: "vocab", word: "せかい", romaji: "sekai",
        meaning: "World", meaningFr: "Monde",
        image: "/kana-mnemonics/word-sekai.webp" },
      { type: "vocab", word: "うそ", romaji: "uso",
        meaning: "Lie", meaningFr: "Mensonge",
        image: "/kana-mnemonics/word-uso.webp" }
    ],
  },
  {
    id: 13, realId: 13, chapter: 1, kind: "practice", drill: true,
    title: "Entraînement : rangée S", subtitle: "Révision rapide さ–そ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 14, realId: 14, chapter: 1, kind: "kana", drill: false,
    title: "ざじずぜぞ", subtitle: "La rangée Z (dakuten de S, じ = ji)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ざ", romaji: "za",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound za." },
      { type: "kana", char: "じ", romaji: "ji",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ji." },
      { type: "kana", char: "ず", romaji: "zu",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound zu." },
      { type: "kana", char: "ぜ", romaji: "ze",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ze." },
      { type: "kana", char: "ぞ", romaji: "zo",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound zo." }
    ],
  },
  {
    id: 15, realId: 15, chapter: 1, kind: "word", drill: false,
    title: "Mots en Z", subtitle: "かぜ, かぞく, すうじ…",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "かぞく", romaji: "kazoku",
        meaning: "Family", meaningFr: "Famille",
        image: "/kana-mnemonics/word-kazoku.webp" },
      { type: "vocab", word: "すうじ", romaji: "suuji",
        meaning: "Number", meaningFr: "Numéro / Nombre",
        image: "/kana-mnemonics/word-suuji.webp" },
      { type: "vocab", word: "すずしい", romaji: "suzushii",
        meaning: "Cool", meaningFr: "Frais",
        image: "/kana-mnemonics/word-suzushii.webp" },
      { type: "vocab", word: "そうじ", romaji: "souji",
        meaning: "Cleaning", meaningFr: "Ménage",
        image: "/kana-mnemonics/word-souji.webp" }
    ],
  },
  {
    id: 16, realId: 16, chapter: 1, kind: "practice", drill: true,
    title: "Entraînement : mots en Z", subtitle: "かぜ, かぞく, すずしい…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 17, realId: 17, chapter: 1, kind: "review", drill: true,
    title: "Révision — Chapitre 1", subtitle: "Tout l'hiragana de base",
    emoji: "🔁", xp: 40, newCount: 0,
    slides: [

    ],
  },
  {
    id: 18, realId: 18, chapter: 2, kind: "kana", drill: false,
    title: "たちつてと", subtitle: "La rangée T (ち = chi, つ = tsu)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "た", romaji: "ta",
        mnemonic: "A friendly tako (octopus) waving a tentacle hello: tako → ta.",
        image: "/kana-mnemonics/ta-tako.webp",
        description: "This hiragana character stands for the sound ta." },
      { type: "kana", char: "ち", romaji: "chi",
        mnemonic: "A cheerleader with a ponytail shouts \"chi-chi-go!\".",
        image: "/kana-mnemonics/chi-cheerleader.webp",
        description: "This hiragana character stands for the sound chi." },
      { type: "kana", char: "つ", romaji: "tsu",
        mnemonic: "A rolling tsunami wave curling on itself: tsu-nami.",
        image: "/kana-mnemonics/tsu-tsunami.webp",
        description: "This hiragana character stands for the sound tsu." },
      { type: "kana", char: "て", romaji: "te",
        mnemonic: "A dog wagging its tail: the tail traces the shape of て.",
        image: "/kana-mnemonics/te-tail.webp",
        description: "This hiragana character stands for the sound te." },
      { type: "kana", char: "と", romaji: "to",
        mnemonic: "A swirling tornado funnel: tornado → to.",
        image: "/kana-mnemonics/to-tornado.webp",
        description: "This hiragana character stands for the sound to." }
    ],
  },
  {
    id: 19, realId: 19, chapter: 2, kind: "word", drill: false,
    title: "Mots en T", subtitle: "Premiers mots avec た–と",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "いち", romaji: "ichi",
        meaning: "one (number)", meaningFr: "Un (chiffre)",
        image: "/kana-mnemonics/word-ichi.webp" },
      { type: "vocab", word: "たこ", romaji: "tako",
        meaning: "Octopus", meaningFr: "Poulpe",
        image: "/kana-mnemonics/word-tako.webp" },
      { type: "vocab", word: "とけい", romaji: "tokei",
        meaning: "Clock", meaningFr: "Horloge",
        image: "/kana-mnemonics/word-tokei.webp" },
      { type: "vocab", word: "くち", romaji: "kuchi",
        meaning: "Mouth", meaningFr: "Bouche",
        image: "/kana-mnemonics/word-kuchi.webp" }
    ],
  },
  {
    id: 20, realId: 20, chapter: 2, kind: "practice", drill: true,
    title: "Entraînement : rangée T", subtitle: "Drille たちつてと",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 21, realId: 21, chapter: 2, kind: "kana", drill: false,
    title: "だぢづでど", subtitle: "La rangée D (dakuten de T)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "だ", romaji: "da",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound da." },
      { type: "kana", char: "ぢ", romaji: "ji",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ji." },
      { type: "kana", char: "づ", romaji: "zu",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound zu." },
      { type: "kana", char: "で", romaji: "de",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound de." },
      { type: "kana", char: "ど", romaji: "do",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound do." }
    ],
  },
  {
    id: 22, realId: 22, chapter: 2, kind: "practice", drill: true,
    title: "Entraînement : rangée D", subtitle: "Drille だ–ど",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 23, realId: 23, chapter: 2, kind: "practice", drill: true,
    title: "Mots en D", subtitle: "どこ, かど, だいがく…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 24, realId: 24, chapter: 2, kind: "kana", drill: false,
    title: "なにぬねの", subtitle: "La rangée N",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "な", romaji: "na",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound na." },
      { type: "kana", char: "に", romaji: "ni",
        mnemonic: "A bent knee seen from the side: knee → ni.",
        image: "/kana-mnemonics/ni-knee.webp",
        description: "This hiragana character stands for the sound ni." },
      { type: "kana", char: "ぬ", romaji: "nu",
        mnemonic: "Noodles twirling around chopsticks: noodles → nu.",
        image: "/kana-mnemonics/nu-noodles.webp",
        description: "This hiragana character stands for the sound nu." },
      { type: "kana", char: "ね", romaji: "ne",
        mnemonic: "A snail with its curled-up shell: snail → ne.",
        image: "/kana-mnemonics/ne-snail.webp",
        description: "This hiragana character stands for the sound ne." },
      { type: "kana", char: "の", romaji: "no",
        mnemonic: "A \"no entry\" sign: circle with a slash: NO → no.",
        image: "/kana-mnemonics/no-nosign.webp",
        description: "This hiragana character stands for the sound no." }
    ],
  },
  {
    id: 25, realId: 25, chapter: 2, kind: "word", drill: false,
    title: "La rangée N & les animaux", subtitle: "ねこ, いぬ, なつ…",
    emoji: "💬", xp: 20, newCount: 5,
    slides: [
      { type: "vocab", word: "ねこ", romaji: "neko",
        meaning: "Cat", meaningFr: "Chat",
        image: "/kana-mnemonics/word-neko.webp" },
      { type: "vocab", word: "いぬ", romaji: "inu",
        meaning: "Dog", meaningFr: "Chien",
        image: "/kana-mnemonics/word-inu.webp" },
      { type: "vocab", word: "さかな", romaji: "sakana",
        meaning: "Fish", meaningFr: "Poisson",
        image: "/kana-mnemonics/word-sakana.webp" },
      { type: "vocab", word: "なつ", romaji: "natsu",
        meaning: "Summer", meaningFr: "Été",
        image: "/kana-mnemonics/word-natsu.webp" },
      { type: "vocab", word: "きのこ", romaji: "kinoko",
        meaning: "Mushroom", meaningFr: "Champignon",
        image: "/kana-mnemonics/word-kinoko.webp" }
    ],
  },
  {
    id: 26, realId: 26, chapter: 2, kind: "practice", drill: true,
    title: "Entraînement : rangée N", subtitle: "Révision rapide な–の",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 27, realId: 27, chapter: 2, kind: "kana", drill: false,
    title: "はひふへほ", subtitle: "La rangée H (ふ = fu)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "は", romaji: "ha",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ha." },
      { type: "kana", char: "ひ", romaji: "hi",
        mnemonic: "A big wide grin going \"hi-hi-hi!\": the mouth traces ひ.",
        image: "/kana-mnemonics/hi-laugh.webp",
        description: "This hiragana character stands for the sound hi." },
      { type: "kana", char: "ふ", romaji: "fu",
        mnemonic: "Mount Fuji with its snow-capped peak: Fuji → fu.",
        image: "/kana-mnemonics/fu-fuji.webp",
        description: "This hiragana character stands for the sound fu." },
      { type: "kana", char: "へ", romaji: "he",
        mnemonic: "An arrow pointing up: heading toward heaven: heaven → he.",
        image: "/kana-mnemonics/he-heaven.webp",
        description: "This hiragana character stands for the sound he." },
      { type: "kana", char: "ほ", romaji: "ho",
        mnemonic: "A friendly horse with a pink mane: horse → ho.",
        image: "/kana-mnemonics/ho-horse.webp",
        description: "This hiragana character stands for the sound ho." }
    ],
  },
  {
    id: 28, realId: 28, chapter: 2, kind: "word", drill: false,
    title: "Mots en H", subtitle: "はな, ひと, ほし…",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "ひと", romaji: "hito",
        meaning: "Person", meaningFr: "Personne",
        image: "/kana-mnemonics/word-hito.webp" },
      { type: "vocab", word: "ふね", romaji: "fune",
        meaning: "Ship", meaningFr: "Bateau",
        image: "/kana-mnemonics/word-fune.webp" },
      { type: "vocab", word: "ほし", romaji: "hoshi",
        meaning: "Star", meaningFr: "Étoile",
        image: "/kana-mnemonics/word-hoshi.webp" },
      { type: "vocab", word: "はい", romaji: "hai",
        meaning: "yes", meaningFr: "Oui",
        image: "/kana-mnemonics/word-hai.webp" }
    ],
  },
  {
    id: 29, realId: 29, chapter: 2, kind: "practice", drill: true,
    title: "Entraînement : rangée H", subtitle: "Drille はひふへほ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 30, realId: 30, chapter: 2, kind: "kana", drill: false,
    title: "ばびぶべぼ", subtitle: "La rangée B (dakuten de H)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ば", romaji: "ba",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ba." },
      { type: "kana", char: "び", romaji: "bi",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound bi." },
      { type: "kana", char: "ぶ", romaji: "bu",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound bu." },
      { type: "kana", char: "べ", romaji: "be",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound be." },
      { type: "kana", char: "ぼ", romaji: "bo",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound bo." }
    ],
  },
  {
    id: 31, realId: 31, chapter: 2, kind: "practice", drill: true,
    title: "Mots en B", subtitle: "そば, ぶた, ぼうし…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 32, realId: 32, chapter: 2, kind: "practice", drill: true,
    title: "Entraînement : rangée B", subtitle: "Drille ば–ぼ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 33, realId: 33, chapter: 2, kind: "kana", drill: false,
    title: "ぱぴぷぺぽ", subtitle: "La rangée P (handakuten de H)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ぱ", romaji: "pa",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound pa." },
      { type: "kana", char: "ぴ", romaji: "pi",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound pi." },
      { type: "kana", char: "ぷ", romaji: "pu",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound pu." },
      { type: "kana", char: "ぺ", romaji: "pe",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound pe." },
      { type: "kana", char: "ぽ", romaji: "po",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound po." }
    ],
  },
  {
    id: 34, realId: 34, chapter: 2, kind: "practice", drill: true,
    title: "Entraînement : rangée P", subtitle: "Révision rapide ぱ–ぽ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 35, realId: 35, chapter: 2, kind: "practice", drill: true,
    title: "Entraînement : rangée P", subtitle: "Du son au caractère",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 36, realId: 36, chapter: 2, kind: "practice", drill: true,
    title: "Formules de politesse", subtitle: "Merci, pardon & se présenter",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 37, realId: 37, chapter: 2, kind: "review", drill: true,
    title: "Révision 2", subtitle: "Révision express · 10 s par tâche",
    emoji: "🔁", xp: 40, newCount: 0,
    slides: [

    ],
  },
  {
    id: 38, realId: 38, chapter: 3, kind: "kana", drill: false,
    title: "まみむめも", subtitle: "La rangée M",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ま", romaji: "ma",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ma." },
      { type: "kana", char: "み", romaji: "mi",
        mnemonic: "A cute music note happily singing: music → mi.",
        image: "/kana-mnemonics/mi-music.webp",
        description: "This hiragana character stands for the sound mi." },
      { type: "kana", char: "む", romaji: "mu",
        mnemonic: "A cow sticking its tongue out: \"moooo!\".",
        image: "/kana-mnemonics/mu-moo.webp",
        description: "This hiragana character stands for the sound mu." },
      { type: "kana", char: "め", romaji: "me",
        mnemonic: "A tangled mess of noodles: what a \"mess\"!",
        image: "/kana-mnemonics/me-mess.webp",
        description: "This hiragana character stands for the sound me." },
      { type: "kana", char: "も", romaji: "mo",
        mnemonic: "A monitor lizard slithering along: monitor → mo.",
        image: "/kana-mnemonics/mo-lizard.webp",
        description: "This hiragana character stands for the sound mo." }
    ],
  },
  {
    id: 39, realId: 39, chapter: 3, kind: "word", drill: false,
    title: "Mots en M", subtitle: "まめ, みみ, むし…",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "みみ", romaji: "mimi",
        meaning: "Ear", meaningFr: "Oreille",
        image: "/kana-mnemonics/word-mimi.webp" },
      { type: "vocab", word: "むし", romaji: "mushi",
        meaning: "Insect", meaningFr: "Insecte",
        image: "/kana-mnemonics/word-mushi.webp" },
      { type: "vocab", word: "もも", romaji: "momo",
        meaning: "Peach", meaningFr: "Pêche",
        image: "/kana-mnemonics/word-momo.webp" },
      { type: "vocab", word: "まち", romaji: "machi",
        meaning: "Town / city", meaningFr: "Ville",
        image: "/kana-mnemonics/word-machi.webp" }
    ],
  },
  {
    id: 40, realId: 40, chapter: 3, kind: "practice", drill: true,
    title: "Entraînement : rangée M", subtitle: "Drille まみむめも",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 41, realId: 41, chapter: 3, kind: "kana", drill: false,
    title: "やゆよ", subtitle: "La rangée Y (seulement 3 caractères)",
    emoji: "🌸", xp: 20, newCount: 3,
    slides: [
      { type: "kana", char: "や", romaji: "ya",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ya." },
      { type: "kana", char: "ゆ", romaji: "yu",
        mnemonic: "A magical unicorn with a pink mane: unicorn → yu.",
        image: "/kana-mnemonics/yu-unicorn.webp",
        description: "This hiragana character stands for the sound yu." },
      { type: "kana", char: "よ", romaji: "yo",
        mnemonic: "A yo-yo dangling from a finger on a string: yo-yo → yo.",
        image: "/kana-mnemonics/yo-yoyo.webp",
        description: "This hiragana character stands for the sound yo." }
    ],
  },
  {
    id: 42, realId: 42, chapter: 3, kind: "word", drill: false,
    title: "Mots en Y", subtitle: "やま, ゆめ, よむ",
    emoji: "💬", xp: 20, newCount: 2,
    slides: [
      { type: "vocab", word: "ゆめ", romaji: "yume",
        meaning: "Dream", meaningFr: "Rêve",
        image: "/kana-mnemonics/word-yume.webp" },
      { type: "vocab", word: "よむ", romaji: "yomu",
        meaning: "to read", meaningFr: "Lire",
        image: "/kana-mnemonics/word-yomu.webp" }
    ],
  },
  {
    id: 43, realId: 43, chapter: 3, kind: "practice", drill: true,
    title: "Entraînement : rangée Y", subtitle: "Drille やゆよ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 44, realId: 44, chapter: 3, kind: "kana", drill: false,
    title: "らりるれろ", subtitle: "La rangée R",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ら", romaji: "ra",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ra." },
      { type: "kana", char: "り", romaji: "ri",
        mnemonic: "A blue river streaming gently down: river → ri.",
        image: "/kana-mnemonics/ri-river.webp",
        description: "This hiragana character stands for the sound ri." },
      { type: "kana", char: "る", romaji: "ru",
        mnemonic: "A hand holding a sparkling ruby: ruby → ru.",
        image: "/kana-mnemonics/ru-ruby.webp",
        description: "This hiragana character stands for the sound ru." },
      { type: "kana", char: "れ", romaji: "re",
        mnemonic: "A reindeer with branching antlers: reindeer → re.",
        image: "/kana-mnemonics/re-reindeer.webp",
        description: "This hiragana character stands for the sound re." },
      { type: "kana", char: "ろ", romaji: "ro",
        mnemonic: "A kitten thief sneaking off with the swag: robbed → ro.",
        image: "/kana-mnemonics/ro-robbed.webp",
        description: "This hiragana character stands for the sound ro." }
    ],
  },
  {
    id: 45, realId: 45, chapter: 3, kind: "practice", drill: true,
    title: "Mots en R", subtitle: "りす, そら, よる",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 46, realId: 46, chapter: 3, kind: "practice", drill: true,
    title: "Entraînement : rangée R", subtitle: "Révision rapide ら–ろ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 47, realId: 47, chapter: 3, kind: "kana", drill: false,
    title: "わをん", subtitle: "Les 3 derniers : rangée W + ん",
    emoji: "🌸", xp: 20, newCount: 7,
    slides: [
      { type: "kana", char: "わ", romaji: "wa",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound wa." },
      { type: "kana", char: "を", romaji: "wo",
        mnemonic: "A person with arms raised going \"whoa!\": rare but striking.",
        image: "/kana-mnemonics/wo-whoa.webp",
        description: "This hiragana character stands for the sound wo." },
      { type: "kana", char: "ん", romaji: "n",
        mnemonic: "A fluffy sleeper humming contentedly in the moonlight: \"nnn…\".",
        image: "/kana-mnemonics/n-night.webp",
        description: "This hiragana character stands for the sound n." },
      { type: "vocab", word: "わに", romaji: "wani",
        meaning: "Crocodile", meaningFr: "Crocodile",
        image: "/kana-mnemonics/word-wani.webp" },
      { type: "vocab", word: "にわ", romaji: "niwa",
        meaning: "Garden", meaningFr: "Jardin",
        image: "/kana-mnemonics/word-niwa.webp" },
      { type: "vocab", word: "かわ", romaji: "kawa",
        meaning: "River", meaningFr: "Rivière",
        image: "/kana-mnemonics/word-kawa.webp" },
      { type: "vocab", word: "みんな", romaji: "minna",
        meaning: "Everyone", meaningFr: "Tout le monde",
        image: "/kana-mnemonics/word-minna.webp" }
    ],
  },
  {
    id: 48, realId: 48, chapter: 3, kind: "practice", drill: true,
    title: "Entraînement : わをん", subtitle: "Drille les derniers hiragana",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 49, realId: 49, chapter: 3, kind: "word", drill: false,
    title: "Mots avec dakuten", subtitle: "でんわ, ぎんこう, だいがく…",
    emoji: "💬", xp: 20, newCount: 3,
    slides: [
      { type: "vocab", word: "ぎんこう", romaji: "ginkou",
        meaning: "Bank", meaningFr: "Banque",
        image: "/kana-mnemonics/word-ginkou.webp" },
      { type: "vocab", word: "だいがく", romaji: "daigaku",
        meaning: "University", meaningFr: "Université",
        image: "/kana-mnemonics/word-daigaku.webp" },
      { type: "vocab", word: "べんきょう", romaji: "benkyou",
        meaning: "Study", meaningFr: "Étude",
        image: "/kana-mnemonics/word-benkyou.webp" }
    ],
  },
  {
    id: 50, realId: 50, chapter: 3, kind: "word", drill: false,
    title: "Se présenter", subtitle: "はじめまして & よろしく",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "せんせい", romaji: "sensei",
        meaning: "Teacher", meaningFr: "Professeur",
        image: "/kana-mnemonics/word-sensei.webp" },
      { type: "vocab", word: "おかあさん", romaji: "okaasan",
        meaning: "Mother", meaningFr: "Mère",
        image: "/kana-mnemonics/word-okaasan.webp" },
      { type: "vocab", word: "はなみ", romaji: "hanami",
        meaning: "Flower viewing", meaningFr: "Contemplation des fleurs (hanami)",
        image: "/kana-mnemonics/word-hanami.webp" },
      { type: "vocab", word: "なまえ", romaji: "namae",
        meaning: "Name", meaningFr: "Nom",
        image: "/kana-mnemonics/word-namae.webp" }
    ],
  },
  {
    id: 51, realId: 51, chapter: 3, kind: "quiz", drill: true,
    title: "Méga Quiz Hiragana", subtitle: "Tout l'hiragana · 10 s par tâche",
    emoji: "🏆", xp: 60, newCount: 0,
    slides: [

    ],
  },
  {
    id: 52, realId: 52, chapter: 4, kind: "kana", drill: false,
    title: "アイウエオ", subtitle: "Les voyelles katakana",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ア", romaji: "a",
        mnemonic: "",
        image: "",
        description: "Le caractère katakana pour le son « a »." },
      { type: "kana", char: "イ", romaji: "i",
        mnemonic: "",
        image: "",
        description: "Le caractère katakana pour le son « i »." },
      { type: "kana", char: "ウ", romaji: "u",
        mnemonic: "",
        image: "",
        description: "Le caractère katakana pour le son « u »." },
      { type: "kana", char: "エ", romaji: "e",
        mnemonic: "",
        image: "",
        description: "Le caractère katakana pour le son « e »." },
      { type: "kana", char: "オ", romaji: "o",
        mnemonic: "",
        image: "",
        description: "Le caractère katakana pour le son « o »." }
    ],
  },
  {
    id: 53, realId: 53, chapter: 4, kind: "word", drill: false,
    title: "Mots-voyelles katakana", subtitle: "アイ, エア…",
    emoji: "💬", xp: 20, newCount: 1,
    slides: [
      { type: "vocab", word: "エア", romaji: "ea",
        meaning: "Air", meaningFr: "Air",
        image: "/kana-mnemonics/word-ea.webp" }
    ],
  },
  {
    id: 54, realId: 54, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : voyelles katakana", subtitle: "Drille ア–オ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 55, realId: 55, chapter: 4, kind: "kana", drill: false,
    title: "カキクケコ", subtitle: "La rangée K (katakana)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "カ", romaji: "ka",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ka." },
      { type: "kana", char: "キ", romaji: "ki",
        mnemonic: "A sharp-cornered key: key → ki.",
        image: "/kana-mnemonics/ki-key.webp",
        description: "This katakana character stands for the sound ki." },
      { type: "kana", char: "ク", romaji: "ku",
        mnemonic: "A right-angled hook: \"kook, that corner is sharp\".",
        image: "/kana-mnemonics/ku-hook.webp",
        description: "This katakana character stands for the sound ku." },
      { type: "kana", char: "ケ", romaji: "ke",
        mnemonic: "A slice of cake (\"cake\" → ケーキ): cake → ke.",
        image: "/kana-mnemonics/ke-cake.webp",
        description: "This katakana character stands for the sound ke." },
      { type: "kana", char: "コ", romaji: "ko",
        mnemonic: "The corner of a cardboard box: two edges of a box.",
        image: "/kana-mnemonics/ko-corner.webp",
        description: "This katakana character stands for the sound ko." }
    ],
  },
  {
    id: 56, realId: 56, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : rangée K", subtitle: "Drille カキクケコ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 57, realId: 57, chapter: 4, kind: "practice", drill: true,
    title: "Mots en K (katakana)", subtitle: "Drille カ–コ et les mots K",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 58, realId: 58, chapter: 4, kind: "kana", drill: false,
    title: "ガギグゲゴ", subtitle: "La rangée G (katakana)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ガ", romaji: "ga",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ga." },
      { type: "kana", char: "ギ", romaji: "gi",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound gi." },
      { type: "kana", char: "グ", romaji: "gu",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound gu." },
      { type: "kana", char: "ゲ", romaji: "ge",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ge." },
      { type: "kana", char: "ゴ", romaji: "go",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound go." }
    ],
  },
  {
    id: 59, realId: 59, chapter: 4, kind: "practice", drill: true,
    title: "Mots en G (katakana)", subtitle: "カギ, ケガ, ギガ…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 60, realId: 60, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : rangée G", subtitle: "Drille ガ–ゴ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 61, realId: 61, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : A, K & G", subtitle: "ア・カ・ガ katakana",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 62, realId: 62, chapter: 4, kind: "kana", drill: false,
    title: "サシスセソ", subtitle: "La rangée S (シ = shi)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "サ", romaji: "sa",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound sa." },
      { type: "kana", char: "シ", romaji: "shi",
        mnemonic: "Three marks = two eyes + smile, turned left: \"she smiles\".",
        image: "/kana-mnemonics/shi-smile.webp",
        description: "This katakana character stands for the sound shi." },
      { type: "kana", char: "ス", romaji: "su",
        mnemonic: "A sleek suit silhouette: suit → su.",
        image: "/kana-mnemonics/su-suit.webp",
        description: "This katakana character stands for the sound su." },
      { type: "kana", char: "セ", romaji: "se",
        mnemonic: "A knight's helmet with visor: \"say hello\" to battle.",
        image: "/kana-mnemonics/se-helmet.webp",
        description: "This katakana character stands for the sound se." },
      { type: "kana", char: "ソ", romaji: "so",
        mnemonic: "A tiny sewing stitch (\"so sew\"): sew → so.",
        image: "/kana-mnemonics/so-stitch.webp",
        description: "This katakana character stands for the sound so." }
    ],
  },
  {
    id: 63, realId: 63, chapter: 4, kind: "practice", drill: true,
    title: "Mots en S (katakana)", subtitle: "ソロ, アイス, スイス…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 64, realId: 64, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : rangée S", subtitle: "Drille サ–ソ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 65, realId: 65, chapter: 4, kind: "kana", drill: false,
    title: "ザジズゼゾ", subtitle: "La rangée Z (katakana, ジ = ji)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ザ", romaji: "za",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound za." },
      { type: "kana", char: "ジ", romaji: "ji",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ji." },
      { type: "kana", char: "ズ", romaji: "zu",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound zu." },
      { type: "kana", char: "ゼ", romaji: "ze",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ze." },
      { type: "kana", char: "ゾ", romaji: "zo",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound zo." }
    ],
  },
  {
    id: 66, realId: 66, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : rangée Z", subtitle: "Drille ザ–ゾ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 67, realId: 67, chapter: 4, kind: "practice", drill: true,
    title: "Mots en Z (katakana)", subtitle: "ガス, アジア…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 68, realId: 68, chapter: 4, kind: "kana", drill: false,
    title: "タチツテト", subtitle: "La rangée T (チ = chi, ツ = tsu)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "タ", romaji: "ta",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ta." },
      { type: "kana", char: "チ", romaji: "chi",
        mnemonic: "A cherry with its stem: cherry → chi.",
        image: "/kana-mnemonics/chi-cherry.webp",
        description: "This katakana character stands for the sound chi." },
      { type: "kana", char: "ツ", romaji: "tsu",
        mnemonic: "Three droplets from a tsunami wave: tsu-nami.",
        image: "/kana-mnemonics/tsu-tsunami.webp",
        description: "This katakana character stands for the sound tsu." },
      { type: "kana", char: "テ", romaji: "te",
        mnemonic: "A telegraph pole with crossbars: telegraph → te.",
        image: "/kana-mnemonics/te-telegraph.webp",
        description: "This katakana character stands for the sound te." },
      { type: "kana", char: "ト", romaji: "to",
        mnemonic: "A totem pole with a flag on top: totem → to.",
        image: "/kana-mnemonics/to-totem.webp",
        description: "This katakana character stands for the sound to." }
    ],
  },
  {
    id: 69, realId: 69, chapter: 4, kind: "practice", drill: true,
    title: "Mots en T (katakana)", subtitle: "テスト, テキスト…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 70, realId: 70, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : rangée T", subtitle: "Drille タ–ト",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 71, realId: 71, chapter: 4, kind: "kana", drill: false,
    title: "ダヂヅデド", subtitle: "La rangée D (katakana)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ダ", romaji: "da",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound da." },
      { type: "kana", char: "ヂ", romaji: "ji",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ji." },
      { type: "kana", char: "ヅ", romaji: "zu",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound zu." },
      { type: "kana", char: "デ", romaji: "de",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound de." },
      { type: "kana", char: "ド", romaji: "do",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound do." }
    ],
  },
  {
    id: 72, realId: 72, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : rangée D", subtitle: "Drille ダ–ド",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 73, realId: 73, chapter: 4, kind: "practice", drill: true,
    title: "Mots en D (katakana)", subtitle: "ドア, ガイド, ダイス…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 74, realId: 74, chapter: 4, kind: "word", drill: false,
    title: "Mots empruntés (katakana)", subtitle: "Les loanwords en japonais",
    emoji: "💬", xp: 20, newCount: 3,
    slides: [
      { type: "vocab", word: "タコス", romaji: "takosu",
        meaning: "Tacos", meaningFr: "Tacos",
        image: "/kana-mnemonics/word-takosu.webp" },
      { type: "vocab", word: "トマト", romaji: "tomato",
        meaning: "Tomato", meaningFr: "Tomate",
        image: "/kana-mnemonics/word-tomato.webp" },
      { type: "vocab", word: "ココア", romaji: "kokoa",
        meaning: "Cocoa", meaningFr: "Cacao",
        image: "/kana-mnemonics/word-kokoa.webp" }
    ],
  },
  {
    id: 75, realId: 75, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : S, Z, T & D", subtitle: "Katakana mixte",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 76, realId: 76, chapter: 4, kind: "kana", drill: false,
    title: "ナニヌネノ", subtitle: "La rangée N (katakana)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ナ", romaji: "na",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound na." },
      { type: "kana", char: "ニ", romaji: "ni",
        mnemonic: "Two parallel lines: ni means \"two\" in Japanese.",
        image: "/kana-mnemonics/ni-two.webp",
        description: "This katakana character stands for the sound ni." },
      { type: "kana", char: "ヌ", romaji: "nu",
        mnemonic: "Noodles twisted around a fork: noodles → nu.",
        image: "/kana-mnemonics/nu-noodles.webp",
        description: "This katakana character stands for the sound nu." },
      { type: "kana", char: "ネ", romaji: "ne",
        mnemonic: "A little church with tower and cross: \"ne\" like neighbourhood.",
        image: "/kana-mnemonics/ne-church.webp",
        description: "This katakana character stands for the sound ne." },
      { type: "kana", char: "ノ", romaji: "no",
        mnemonic: "A single diagonal slash: a clear \"NO\".",
        image: "/kana-mnemonics/no-slash.webp",
        description: "This katakana character stands for the sound no." }
    ],
  },
  {
    id: 77, realId: 77, chapter: 4, kind: "practice", drill: true,
    title: "Mots en N (katakana)", subtitle: "ナイス, カナダ, テニス…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 78, realId: 78, chapter: 4, kind: "practice", drill: true,
    title: "Entraînement : rangée N", subtitle: "Drille ナ–ノ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 79, realId: 79, chapter: 4, kind: "review", drill: true,
    title: "Révision 3", subtitle: "Révision express · 10 s par tâche",
    emoji: "🔁", xp: 40, newCount: 0,
    slides: [

    ],
  },
  {
    id: 80, realId: 80, chapter: 5, kind: "kana", drill: false,
    title: "ハヒフヘホ", subtitle: "La rangée H (フ = fu)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ハ", romaji: "ha",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ha." },
      { type: "kana", char: "ヒ", romaji: "hi",
        mnemonic: "A small hill with a flag on top: hill → hi.",
        image: "/kana-mnemonics/hi-hill.webp",
        description: "This katakana character stands for the sound hi." },
      { type: "kana", char: "フ", romaji: "fu",
        mnemonic: "A hockey-stick hook: \"foo\"tball-like shape.",
        image: "/kana-mnemonics/fu-hockey.webp",
        description: "This katakana character stands for the sound fu." },
      { type: "kana", char: "ヘ", romaji: "he",
        mnemonic: "A pointed mountain peak rising toward the sky: heaven → he.",
        image: "/kana-mnemonics/he-mountain.webp",
        description: "This katakana character stands for the sound he." },
      { type: "kana", char: "ホ", romaji: "ho",
        mnemonic: "A TV antenna with four little arms: \"ho, ho, ho, ho\".",
        image: "/kana-mnemonics/ho-tv.webp",
        description: "This katakana character stands for the sound ho." }
    ],
  },
  {
    id: 81, realId: 81, chapter: 5, kind: "practice", drill: true,
    title: "Mots en H (katakana)", subtitle: "ハイ, ヘイト…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 82, realId: 82, chapter: 5, kind: "practice", drill: true,
    title: "Entraînement : rangée H", subtitle: "Drille ハ–ホ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 83, realId: 83, chapter: 5, kind: "kana", drill: false,
    title: "バビブベボ", subtitle: "La rangée B (katakana)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "バ", romaji: "ba",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ba." },
      { type: "kana", char: "ビ", romaji: "bi",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound bi." },
      { type: "kana", char: "ブ", romaji: "bu",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound bu." },
      { type: "kana", char: "ベ", romaji: "be",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound be." },
      { type: "kana", char: "ボ", romaji: "bo",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound bo." }
    ],
  },
  {
    id: 84, realId: 84, chapter: 5, kind: "practice", drill: true,
    title: "Entraînement : rangée B", subtitle: "Drille バ–ボ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 85, realId: 85, chapter: 5, kind: "practice", drill: true,
    title: "Mots en B (katakana)", subtitle: "バス, ビザ, バナナ…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 86, realId: 86, chapter: 5, kind: "kana", drill: false,
    title: "パピプペポ", subtitle: "La rangée P (handakuten)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "パ", romaji: "pa",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound pa." },
      { type: "kana", char: "ピ", romaji: "pi",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound pi." },
      { type: "kana", char: "プ", romaji: "pu",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound pu." },
      { type: "kana", char: "ペ", romaji: "pe",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound pe." },
      { type: "kana", char: "ポ", romaji: "po",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound po." }
    ],
  },
  {
    id: 87, realId: 87, chapter: 5, kind: "practice", drill: true,
    title: "Mots en P (katakana)", subtitle: "パス, ピザ, ポスト…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 88, realId: 88, chapter: 5, kind: "practice", drill: true,
    title: "Entraînement : rangée P", subtitle: "Drille パ–ポ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 89, realId: 89, chapter: 5, kind: "kana", drill: false,
    title: "マミムメモ", subtitle: "La rangée M (katakana)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "マ", romaji: "ma",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ma." },
      { type: "kana", char: "ミ", romaji: "mi",
        mnemonic: "Three cat whiskers: mi sounds like a cat's \"meow\".",
        image: "/kana-mnemonics/mi-three.webp",
        description: "This katakana character stands for the sound mi." },
      { type: "kana", char: "ム", romaji: "mu",
        mnemonic: "A cow with a little tail: \"moooo\".",
        image: "/kana-mnemonics/mu-cow.webp",
        description: "This katakana character stands for the sound mu." },
      { type: "kana", char: "メ", romaji: "me",
        mnemonic: "Two crossed swords: \"me\" as in medal of honor.",
        image: "/kana-mnemonics/me-medal.webp",
        description: "This katakana character stands for the sound me." },
      { type: "kana", char: "モ", romaji: "mo",
        mnemonic: "A hook with three loops: \"mo\" more fish!",
        image: "/kana-mnemonics/mo-fishhook.webp",
        description: "This katakana character stands for the sound mo." }
    ],
  },
  {
    id: 90, realId: 90, chapter: 5, kind: "practice", drill: true,
    title: "Entraînement : rangée M", subtitle: "Drille マ–モ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 91, realId: 91, chapter: 5, kind: "practice", drill: true,
    title: "Mots en M (katakana)", subtitle: "Drille マミムメモ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 92, realId: 92, chapter: 5, kind: "word", drill: false,
    title: "Mots du quotidien (katakana)", subtitle: "couteau, masque…",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "メモ", romaji: "memo",
        meaning: "Memo", meaningFr: "Mémo",
        image: "/kana-mnemonics/word-memo.webp" },
      { type: "vocab", word: "ナイフ", romaji: "naifu",
        meaning: "Knife", meaningFr: "Couteau",
        image: "/kana-mnemonics/word-naifu.webp" },
      { type: "vocab", word: "マスク", romaji: "masuku",
        meaning: "Mask", meaningFr: "Masque",
        image: "/kana-mnemonics/word-masuku.webp" },
      { type: "vocab", word: "テニス", romaji: "tenisu",
        meaning: "Tennis", meaningFr: "Tennis",
        image: "/kana-mnemonics/word-tenisu.webp" }
    ],
  },
  {
    id: 93, realId: 93, chapter: 5, kind: "practice", drill: true,
    title: "Entraînement : H, B, P & M", subtitle: "Katakana mixte",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 94, realId: 94, chapter: 5, kind: "kana", drill: false,
    title: "ヤユヨ", subtitle: "La rangée Y (katakana)",
    emoji: "🌸", xp: 20, newCount: 3,
    slides: [
      { type: "kana", char: "ヤ", romaji: "ya",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ya." },
      { type: "kana", char: "ユ", romaji: "yu",
        mnemonic: "A U-shaped tool: unique → yu.",
        image: "/kana-mnemonics/yu-wrench.webp",
        description: "This katakana character stands for the sound yu." },
      { type: "kana", char: "ヨ", romaji: "yo",
        mnemonic: "A yo-yo rack with three slots: yo → yo.",
        image: "/kana-mnemonics/yo-yoyo.webp",
        description: "This katakana character stands for the sound yo." }
    ],
  },
  {
    id: 95, realId: 95, chapter: 5, kind: "practice", drill: true,
    title: "Mots en Y (katakana)", subtitle: "ヨガ, マヨ, ヤク",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 96, realId: 96, chapter: 5, kind: "practice", drill: true,
    title: "Entraînement : rangée Y", subtitle: "Drille ヤ・ユ・ヨ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 97, realId: 97, chapter: 5, kind: "kana", drill: false,
    title: "ラリルレロ", subtitle: "La rangée R (katakana)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "kana", char: "ラ", romaji: "ra",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ra." },
      { type: "kana", char: "リ", romaji: "ri",
        mnemonic: "Two upright bamboo reeds: reed → ri.",
        image: "/kana-mnemonics/ri-reed.webp",
        description: "This katakana character stands for the sound ri." },
      { type: "kana", char: "ル", romaji: "ru",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound ru." },
      { type: "kana", char: "レ", romaji: "re",
        mnemonic: "A check mark on a receipt: receipt → re.",
        image: "/kana-mnemonics/re-receipt.webp",
        description: "This katakana character stands for the sound re." },
      { type: "kana", char: "ロ", romaji: "ro",
        mnemonic: "A square road block seen from above: road → ro.",
        image: "/kana-mnemonics/ro-road.webp",
        description: "This katakana character stands for the sound ro." }
    ],
  },
  {
    id: 98, realId: 98, chapter: 5, kind: "practice", drill: true,
    title: "Entraînement : rangée R", subtitle: "Drille ラ–ロ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 99, realId: 99, chapter: 5, kind: "practice", drill: true,
    title: "Mots en R (katakana)", subtitle: "Drille ラリルレロ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 100, realId: 100, chapter: 5, kind: "kana", drill: false,
    title: "ワヲン", subtitle: "Les derniers katakana",
    emoji: "🌸", xp: 20, newCount: 3,
    slides: [
      { type: "kana", char: "ワ", romaji: "wa",
        mnemonic: "",
        image: "",
        description: "This katakana character stands for the sound wa." },
      { type: "kana", char: "ヲ", romaji: "wo",
        mnemonic: "Like を: rare, a \"whoa\" figure with arms raised.",
        image: "/kana-mnemonics/wo-whoa.webp",
        description: "This katakana character stands for the sound wo." },
      { type: "kana", char: "ン", romaji: "n",
        mnemonic: "A tiny flick toward the upper-left: \"hmm-n?\".",
        image: "/kana-mnemonics/n-flick.webp",
        description: "This katakana character stands for the sound n." }
    ],
  },
  {
    id: 101, realId: 101, chapter: 5, kind: "practice", drill: true,
    title: "Mots en W & ン", subtitle: "ワイン, メロン, アイロン…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 102, realId: 102, chapter: 5, kind: "practice", drill: true,
    title: "Entraînement : ワ・ン", subtitle: "Drille les derniers katakana",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 103, realId: 103, chapter: 5, kind: "word", drill: false,
    title: "Mots katakana avec dakuten", subtitle: "バス, ビール, ゲーム…",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "ビール", romaji: "biiru",
        meaning: "Beer", meaningFr: "Bière",
        image: "/kana-mnemonics/word-biiru.webp" },
      { type: "vocab", word: "ゲーム", romaji: "geemu",
        meaning: "Game", meaningFr: "Jeu",
        image: "/kana-mnemonics/word-geemu.webp" },
      { type: "vocab", word: "ドア", romaji: "doa",
        meaning: "Door", meaningFr: "Porte",
        image: "/kana-mnemonics/word-doa.webp" },
      { type: "vocab", word: "パン", romaji: "pan",
        meaning: "Bread", meaningFr: "Pain",
        image: "/kana-mnemonics/word-pan.webp" }
    ],
  },
  {
    id: 104, realId: 104, chapter: 5, kind: "practice", drill: true,
    title: "Entraînement : dakuten katakana", subtitle: "Drille les sons voisés",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 105, realId: 105, chapter: 5, kind: "quiz", drill: true,
    title: "Méga Quiz Katakana", subtitle: "Tout le katakana · 10 s par tâche",
    emoji: "🏆", xp: 60, newCount: 0,
    slides: [

    ],
  },
  {
    id: 106, realId: 106, chapter: 6, kind: "kana", drill: false,
    title: "Petit っ / ッ", subtitle: "Les consonnes doubles (sokuon)",
    emoji: "🌸", xp: 20, newCount: 5,
    slides: [
      { type: "vocab", word: "きって", romaji: "kitte",
        meaning: "Stamp", meaningFr: "Timbre",
        image: "" },
      { type: "vocab", word: "きっぷ", romaji: "kippu",
        meaning: "Ticket", meaningFr: "Billet / Ticket",
        image: "" },
      { type: "vocab", word: "ざっし", romaji: "zasshi",
        meaning: "Magazine", meaningFr: "Magazine",
        image: "" },
      { type: "vocab", word: "がっこう", romaji: "gakkou",
        meaning: "School", meaningFr: "École",
        image: "" },
      { type: "vocab", word: "ニッポン", romaji: "nippon",
        meaning: "Japan", meaningFr: "Japon",
        image: "" }
    ],
  },
  {
    id: 107, realId: 107, chapter: 6, kind: "kana", drill: false,
    title: "しゃ・ちゃ", subtitle: "Yōon : sha, shu, sho, cha, chu, cho",
    emoji: "🌸", xp: 20, newCount: 6,
    slides: [
      { type: "kana", char: "しゃ", romaji: "sha",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound sha." },
      { type: "kana", char: "しゅ", romaji: "shu",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound shu." },
      { type: "kana", char: "しょ", romaji: "sho",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound sho." },
      { type: "kana", char: "ちゃ", romaji: "cha",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound cha." },
      { type: "kana", char: "ちゅ", romaji: "chu",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound chu." },
      { type: "kana", char: "ちょ", romaji: "cho",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound cho." }
    ],
  },
  {
    id: 108, realId: 108, chapter: 6, kind: "kana", drill: false,
    title: "きゃ・にゃ・りゃ", subtitle: "Yōon : kya, nya, rya…",
    emoji: "🌸", xp: 20, newCount: 8,
    slides: [
      { type: "kana", char: "きゅ", romaji: "kyu",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound kyu." },
      { type: "kana", char: "きょ", romaji: "kyo",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound kyo." },
      { type: "kana", char: "にゃ", romaji: "nya",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound nya." },
      { type: "kana", char: "にゅ", romaji: "nyu",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound nyu." },
      { type: "kana", char: "にょ", romaji: "nyo",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound nyo." },
      { type: "kana", char: "りゃ", romaji: "rya",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound rya." },
      { type: "kana", char: "りゅ", romaji: "ryu",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ryu." },
      { type: "kana", char: "りょ", romaji: "ryo",
        mnemonic: "",
        image: "",
        description: "This hiragana character stands for the sound ryo." }
    ],
  },
  {
    id: 109, realId: 109, chapter: 6, kind: "word", drill: false,
    title: "Mots avec yōon", subtitle: "おちゃ, しゃしん…",
    emoji: "💬", xp: 20, newCount: 3,
    slides: [
      { type: "vocab", word: "きょう", romaji: "kyou",
        meaning: "Today", meaningFr: "Aujourd'hui",
        image: "" },
      { type: "vocab", word: "しゃしん", romaji: "shashin",
        meaning: "Photo", meaningFr: "Photo",
        image: "" },
      { type: "vocab", word: "りょこう", romaji: "ryokou",
        meaning: "Travel", meaningFr: "Voyage",
        image: "" }
    ],
  },
  {
    id: 110, realId: 110, chapter: 6, kind: "practice", drill: true,
    title: "Entraînement : yōon", subtitle: "Drille les sons contractés",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 111, realId: 111, chapter: 6, kind: "kana", drill: false,
    title: "Voyelles longues ー", subtitle: "コーヒー, ケーキ, ラーメン",
    emoji: "🌸", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "ケーキ", romaji: "keeki",
        meaning: "Cake", meaningFr: "Gâteau",
        image: "" },
      { type: "vocab", word: "ラーメン", romaji: "raamen",
        meaning: "Ramen", meaningFr: "Ramen",
        image: "" },
      { type: "vocab", word: "ゲーム", romaji: "geemu",
        meaning: "Game", meaningFr: "Jeu",
        image: "" },
      { type: "vocab", word: "スーパー", romaji: "suupaa",
        meaning: "Supermarket", meaningFr: "Supermarché",
        image: "" }
    ],
  },
  {
    id: 112, realId: 112, chapter: 6, kind: "word", drill: false,
    title: "Grands mots empruntés", subtitle: "チョコレート, ジュース…",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "ジュース", romaji: "juusu",
        meaning: "Juice", meaningFr: "Jus",
        image: "" },
      { type: "vocab", word: "シャワー", romaji: "shawaa",
        meaning: "Shower", meaningFr: "Douche",
        image: "" },
      { type: "vocab", word: "レストラン", romaji: "resutoran",
        meaning: "Restaurant", meaningFr: "Restaurant",
        image: "" },
      { type: "vocab", word: "コンピューター", romaji: "konpyuutaa",
        meaning: "Computer", meaningFr: "Ordinateur",
        image: "" }
    ],
  },
  {
    id: 113, realId: 113, chapter: 6, kind: "practice", drill: true,
    title: "Entraînement : voyelles longues & loanwords", subtitle: "コーヒー, チョコレート…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 114, realId: 114, chapter: 6, kind: "practice", drill: true,
    title: "Entraînement : sons spéciaux", subtitle: "Drille っ, yōon & voyelles longues",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 115, realId: 115, chapter: 6, kind: "quiz", drill: true,
    title: "Méga Quiz Kana", subtitle: "Hiragana + katakana + dakuten + yōon",
    emoji: "🏆", xp: 60, newCount: 0,
    slides: [

    ],
  },
  {
    id: 116, realId: 116, chapter: 7, kind: "word", drill: false,
    title: "Nombres 1–5 + Kanji", subtitle: "ichi–go et 一・二・三・四・五",
    emoji: "💬", xp: 20, newCount: 5,
    slides: [
      { type: "vocab", word: "いち", romaji: "ichi",
        meaning: "Un (一)", meaningFr: "Un (一)",
        image: "" },
      { type: "vocab", word: "に", romaji: "ni",
        meaning: "Deux (二)", meaningFr: "Deux (二)",
        image: "" },
      { type: "vocab", word: "さん", romaji: "san",
        meaning: "Trois (三)", meaningFr: "Trois (三)",
        image: "" },
      { type: "vocab", word: "よん", romaji: "yon",
        meaning: "Quatre (四)", meaningFr: "Quatre (四)",
        image: "" },
      { type: "vocab", word: "ご", romaji: "go",
        meaning: "Cinq (五)", meaningFr: "Cinq (五)",
        image: "" }
    ],
  },
  {
    id: 117, realId: 117, chapter: 7, kind: "word", drill: false,
    title: "Nombres 6–10 + Kanji", subtitle: "roku–juu et 六七八九十",
    emoji: "💬", xp: 20, newCount: 9,
    slides: [
      { type: "vocab", word: "なな", romaji: "nana",
        meaning: "Seven", meaningFr: "Sept",
        image: "" },
      { type: "vocab", word: "はち", romaji: "hachi",
        meaning: "Eight", meaningFr: "Huit",
        image: "" },
      { type: "vocab", word: "きゅう", romaji: "kyuu",
        meaning: "Nine", meaningFr: "Neuf",
        image: "" },
      { type: "vocab", word: "じゅう", romaji: "juu",
        meaning: "Ten", meaningFr: "Dix",
        image: "" },
      { type: "vocab", word: "六", romaji: "roku",
        meaning: "Six (Kanji)", meaningFr: "Six (六)",
        image: "" },
      { type: "vocab", word: "七", romaji: "nana",
        meaning: "Seven (Kanji)", meaningFr: "Sept (七)",
        image: "" },
      { type: "vocab", word: "八", romaji: "hachi",
        meaning: "Eight (Kanji)", meaningFr: "Huit (八)",
        image: "" },
      { type: "vocab", word: "九", romaji: "kyuu",
        meaning: "Nine (Kanji)", meaningFr: "Neuf (九)",
        image: "" },
      { type: "vocab", word: "十", romaji: "juu",
        meaning: "Ten (Kanji)", meaningFr: "Dix (十)",
        image: "" }
    ],
  },
  {
    id: 118, realId: 118, chapter: 7, kind: "practice", drill: true,
    title: "Entraînement : les nombres", subtitle: "Drille 1–10 et les kanji",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 119, realId: 119, chapter: 8, kind: "word", drill: false,
    title: "Compteurs ～つ", subtitle: "ひとつ, ふたつ, みっつ…",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "ひとつ", romaji: "hitotsu",
        meaning: "Une chose", meaningFr: "Une chose",
        image: "" },
      { type: "vocab", word: "ふたつ", romaji: "futatsu",
        meaning: "Deux choses", meaningFr: "Deux choses",
        image: "" },
      { type: "vocab", word: "みっつ", romaji: "mittsu",
        meaning: "Trois choses", meaningFr: "Trois choses",
        image: "" },
      { type: "vocab", word: "よっつ", romaji: "yottsu",
        meaning: "Quatre choses", meaningFr: "Quatre choses",
        image: "" }
    ],
  },
  {
    id: 120, realId: 120, chapter: 8, kind: "word", drill: false,
    title: "Compteurs", subtitle: "～にん, ～こ : personnes & objets",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "ふたり", romaji: "futari",
        meaning: "Two people", meaningFr: "Deux personnes",
        image: "" },
      { type: "vocab", word: "さんにん", romaji: "sannin",
        meaning: "Three people", meaningFr: "Trois personnes",
        image: "" },
      { type: "vocab", word: "いっこ", romaji: "ikko",
        meaning: "One piece", meaningFr: "Un objet",
        image: "" },
      { type: "vocab", word: "にこ", romaji: "niko",
        meaning: "Two pieces", meaningFr: "Deux objets",
        image: "" }
    ],
  },
  {
    id: 121, realId: 121, chapter: 8, kind: "practice", drill: true,
    title: "Entraînement : compteurs", subtitle: "Drille ～にん, ～こ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 122, realId: 122, chapter: 8, kind: "word", drill: false,
    title: "Quel âge as-tu ?", subtitle: "なんさいですか？ ＿さいです",
    emoji: "💬", xp: 20, newCount: 1,
    slides: [
      { type: "vocab", word: "＿さいです", romaji: "_ sai desu",
        meaning: "I am _ years old", meaningFr: "J'ai _ ans",
        image: "" }
    ],
  },
  {
    id: 123, realId: 123, chapter: 8, kind: "word", drill: false,
    title: "Quelle heure est-il ?", subtitle: "いまなんじですか",
    emoji: "💬", xp: 20, newCount: 5,
    slides: [
      { type: "vocab", word: "にじ", romaji: "niji",
        meaning: "Two o'clock", meaningFr: "Deux heures",
        image: "" },
      { type: "vocab", word: "さんじ", romaji: "sanji",
        meaning: "Three o'clock", meaningFr: "Trois heures",
        image: "" },
      { type: "vocab", word: "ごぜん", romaji: "gozen",
        meaning: "AM / Morning", meaningFr: "Matin (AM)",
        image: "" },
      { type: "vocab", word: "ごご", romaji: "gogo",
        meaning: "PM / Afternoon", meaningFr: "Après-midi (PM)",
        image: "" },
      { type: "vocab", word: "いまなんじですか", romaji: "ima nanji desu ka",
        meaning: "What time is it now?", meaningFr: "Quelle heure est-il ?",
        image: "" }
    ],
  },
  {
    id: 124, realId: 124, chapter: 8, kind: "practice", drill: true,
    title: "Entraînement : âge & heure", subtitle: "Drille なんさい・なんじ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 125, realId: 125, chapter: 8, kind: "practice", drill: true,
    title: "Entraînement : nombres & heure", subtitle: "Révision avant le quiz",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 126, realId: 126, chapter: 8, kind: "quiz", drill: true,
    title: "Méga Quiz Compteurs", subtitle: "Nombres, compteurs & heure",
    emoji: "🏆", xp: 60, newCount: 0,
    slides: [

    ],
  },
  {
    id: 127, realId: 127, chapter: 9, kind: "word", drill: false,
    title: "これ・それ・あれ", subtitle: "Ceci, cela, là-bas (par distance)",
    emoji: "💬", xp: 20, newCount: 4,
    slides: [
      { type: "vocab", word: "これ", romaji: "kore",
        meaning: "This (here)", meaningFr: "Ceci (ici)",
        image: "" },
      { type: "vocab", word: "それ", romaji: "sore",
        meaning: "That (there)", meaningFr: "Cela (là)",
        image: "" },
      { type: "vocab", word: "あれ", romaji: "are",
        meaning: "That (over there)", meaningFr: "Cela (là-bas)",
        image: "" },
      { type: "vocab", word: "これはなんですか", romaji: "kore wa nan desu ka",
        meaning: "What is this?", meaningFr: "Qu'est-ce que c'est ?",
        image: "" }
    ],
  },
  {
    id: 128, realId: 128, chapter: 9, kind: "practice", drill: true,
    title: "Entraînement : これ・それ・あれ", subtitle: "Par distance",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 129, realId: 129, chapter: 9, kind: "practice", drill: true,
    title: "Entraînement : démonstratifs", subtitle: "Drille これ・それ・あれ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 130, realId: 130, chapter: 9, kind: "practice", drill: true,
    title: "Entraînement : ここ・そこ・あそこ", subtitle: "Lieux + どこですか",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 131, realId: 131, chapter: 9, kind: "word", drill: false,
    title: "Mots interrogatifs", subtitle: "なに, だれ, どこ, いつ, どれ",
    emoji: "💬", xp: 20, newCount: 5,
    slides: [
      { type: "vocab", word: "だれ", romaji: "dare",
        meaning: "Who?", meaningFr: "Qui ?",
        image: "" },
      { type: "vocab", word: "どこ", romaji: "doko",
        meaning: "Where?", meaningFr: "Où ?",
        image: "" },
      { type: "vocab", word: "いつ", romaji: "itsu",
        meaning: "When?", meaningFr: "Quand ?",
        image: "" },
      { type: "vocab", word: "どれ", romaji: "dore",
        meaning: "Which one?", meaningFr: "Lequel ?",
        image: "" },
      { type: "vocab", word: "＿はどこですか", romaji: "_ wa doko desu ka",
        meaning: "Where is _?", meaningFr: "Où est _ ?",
        image: "" }
    ],
  },
  {
    id: 132, realId: 132, chapter: 9, kind: "word", drill: false,
    title: "Langues & origine", subtitle: "にほんご, ドイツご, にほんじん",
    emoji: "💬", xp: 20, newCount: 6,
    slides: [
      { type: "vocab", word: "えいご", romaji: "eigo",
        meaning: "English", meaningFr: "Anglais",
        image: "" },
      { type: "vocab", word: "ドイツご", romaji: "doitsugo",
        meaning: "German", meaningFr: "Allemand",
        image: "" },
      { type: "vocab", word: "にほんじん", romaji: "nihonjin",
        meaning: "Japanese person", meaningFr: "Japonais(e)",
        image: "" },
      { type: "vocab", word: "ドイツじん", romaji: "doitsujin",
        meaning: "German person", meaningFr: "Allemand(e)",
        image: "" },
      { type: "vocab", word: "にほんごをべんきょうしています", romaji: "nihongo o benkyou shite imasu",
        meaning: "I'm studying Japanese", meaningFr: "J'étudie le japonais",
        image: "" },
      { type: "vocab", word: "＿からきました", romaji: "_ kara kimashita",
        meaning: "I'm from _", meaningFr: "Je viens de _",
        image: "" }
    ],
  },
  {
    id: 133, realId: 133, chapter: 9, kind: "practice", drill: true,
    title: "Entraînement : questions", subtitle: "Drille les mots interrogatifs",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 134, realId: 134, chapter: 9, kind: "review", drill: true,
    title: "Révision — Unité 9", subtitle: "Révision express · 10 s par tâche",
    emoji: "🔁", xp: 40, newCount: 0,
    slides: [

    ],
  },
  {
    id: 135, realId: 135, chapter: 10, kind: "word", drill: false,
    title: "Achats & commande", subtitle: "いくらですか, ください",
    emoji: "💬", xp: 20, newCount: 6,
    slides: [
      { type: "vocab", word: "みせ", romaji: "mise",
        meaning: "Shop", meaningFr: "Magasin",
        image: "" },
      { type: "vocab", word: "えん", romaji: "en",
        meaning: "Yen", meaningFr: "Yen",
        image: "" },
      { type: "vocab", word: "きっぷ", romaji: "kippu",
        meaning: "Ticket", meaningFr: "Billet / Ticket",
        image: "" },
      { type: "vocab", word: "おみやげ", romaji: "omiyage",
        meaning: "Souvenir", meaningFr: "Souvenir",
        image: "" },
      { type: "vocab", word: "いくらですか", romaji: "ikura desu ka",
        meaning: "How much is it?", meaningFr: "Combien ça coûte ?",
        image: "" },
      { type: "vocab", word: "これをください", romaji: "kore o kudasai",
        meaning: "This one please", meaningFr: "Celui-ci, s'il vous plaît",
        image: "" }
    ],
  },
  {
    id: 136, realId: 136, chapter: 10, kind: "practice", drill: true,
    title: "Maison & repas", subtitle: "ただいま, いただきます…",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 137, realId: 137, chapter: 10, kind: "practice", drill: true,
    title: "Entraînement : maison & achats", subtitle: "Drille ただいま, いただきます & achats",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 138, realId: 138, chapter: 10, kind: "word", drill: false,
    title: "Se déplacer", subtitle: "でんしゃ, えき, みぎ, ひだり",
    emoji: "💬", xp: 20, newCount: 5,
    slides: [
      { type: "vocab", word: "えき", romaji: "eki",
        meaning: "Station", meaningFr: "Gare",
        image: "" },
      { type: "vocab", word: "みぎ", romaji: "migi",
        meaning: "Right", meaningFr: "Droite",
        image: "" },
      { type: "vocab", word: "ひだり", romaji: "hidari",
        meaning: "Left", meaningFr: "Gauche",
        image: "" },
      { type: "vocab", word: "まっすぐ", romaji: "massugu",
        meaning: "Straight ahead", meaningFr: "Tout droit",
        image: "" },
      { type: "vocab", word: "だいじょうぶ", romaji: "daijoubu",
        meaning: "It's okay / I'm fine", meaningFr: "Ça va / Tout va bien",
        image: "" }
    ],
  },
  {
    id: 139, realId: 139, chapter: 10, kind: "practice", drill: true,
    title: "Entraînement : se déplacer", subtitle: "Drille えき, みぎ, ひだり, まっすぐ",
    emoji: "📝", xp: 15, newCount: 0,
    slides: [

    ],
  },
  {
    id: 140, realId: 140, chapter: 10, kind: "review", drill: true,
    title: "Révision du quotidien", subtitle: "Révision express · 10 s par tâche",
    emoji: "🔁", xp: 40, newCount: 0,
    slides: [

    ],
  },
  {
    id: 141, realId: 141, chapter: 10, kind: "quiz", drill: true,
    title: "Méga Quiz Final", subtitle: "Le grand test final · 10 s par tâche",
    emoji: "🏆", xp: 100, newCount: 0,
    slides: [

    ],
  }
];

export function getLesson(id: number): BasicsLesson | null {
  return ALL_LESSONS.find(l => l.id === id) ?? null;
}

export function lessonsByChapter(chapter: number): BasicsLesson[] {
  return ALL_LESSONS.filter(l => l.chapter === chapter);
}

// Chapitres réellement présents dans le contenu récupéré (avec au moins 1 leçon).
export const CHAPTERS_WITH_LESSONS: BasicsChapter[] =
  BASICS_CHAPTERS.filter(c => ALL_LESSONS.some(l => l.chapter === c.num));

// Rétro-compat : ancien export utilisé ailleurs.
export const CHAPTER1_LESSONS = lessonsByChapter(1);
