const POI_LOGOS: Partial<Record<string, string>> = {
  "jr-shinjuku":              "/images/pois/logos/jr-shinjuku.svg",
  "tokyo-station-shinkansen": "/images/pois/logos/shinkansen.png",
  "haneda-airport":           "/images/pois/logos/haneda.png",
  "7eleven-shinjuku":         "/images/pois/logos/7eleven.png",
  "familymart-shibuya":       "/images/pois/logos/familymart.webp",
  "lawson-harajuku":          "/images/pois/logos/lawson.png",
  "donquijote-shibuya":       "/images/pois/logos/donquijote.webp",
  "loft-shibuya":             "/images/pois/logos/loft.png",
  "shibuya-109":              "/images/pois/logos/shibuya109.png",
  "yodobashi-akiba":          "/images/pois/logos/yodobashi.jpg",
  "lumine-est-shinjuku":      "/images/pois/logos/lumine.jpg",
  "mcdonalds-shibuya":        "/images/pois/logos/mcdonalds.png",
  "starbucks-shibuya":        "/images/pois/logos/starbucks.png",
  "nine-hours-shinjuku":      "/images/pois/logos/nine-hours.jpg",
  "grand-hyatt-tokyo":        "/images/pois/logos/grand-hyatt.jpg",
  "matsumoto-kiyoshi-akiba":  "/images/pois/logos/matsumoto-kiyoshi.jpg",
  "tokyo-central-post":       "/images/pois/logos/tokyo-post.png",
  "tokyo-skytree":            "/images/pois/logos/tokyo-skytree.png",
  "tokyo-tower":              "/images/pois/logos/tokyo-tower.png",
  "tokyo-national-museum":    "/images/pois/logos/tokyo-national-museum.png",
  "asahi-super-dry-hall":     "/images/pois/logos/asahi.png",
  "big-echo-kabukicho":       "/images/pois/logos/big-echo.webp",
  "at-home-cafe-akihabara":   "/images/pois/logos/at-home-cafe.webp",
};

export default POI_LOGOS;
